[keyboard]
bindings = [
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "I", mods = "Control", chars = "\u001b[105;5u" },
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
