#!/bin/bash
# Auto-generated by pywal — do not edit
export BAR_COLOR="0x80{background.strip}"
export FOREGROUND="0xff{foreground.strip}"
export INACTIVE="0xff{color8.strip}"
export ACCENT="0xff{color4.strip}"
export ALERT="0xff{color1.strip}"
export HIGHLIGHT="0xff{color6.strip}"
export SUBTLE="0x40{foreground.strip}"
