#!/usr/bin/env bash
export FIFO_UEBERZUG="/tmp/lf-ueberzug-${PPID}"

function cleanup {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -KILL -P $$
}

mkfifo "$FIFO_UEBERZUG"
trap cleanup EXIT
ueberzugpp layer --silent --parser json < "$FIFO_UEBERZUG" &

lf $@
